# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFly < Formula
  desc "Fast CLI to jump to local git repos by name"
  homepage "https://github.com/TheOneWithTheWrench/go-fly"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheOneWithTheWrench/go-fly/releases/download/v0.1.5/go-fly_darwin_amd64.tar.gz"
      sha256 "59de221537109d979388a876eaa6b5a08418bded4654f72f2b1a2d520019e643"

      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheOneWithTheWrench/go-fly/releases/download/v0.1.5/go-fly_darwin_arm64.tar.gz"
      sha256 "923dac4636288a499cccf2120efc2aa3a78124980fcd06442a14be0c5e40a3e3"

      define_method(:install) do
        bin.install "fly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOneWithTheWrench/go-fly/releases/download/v0.1.5/go-fly_linux_amd64.tar.gz"
      sha256 "b08a005bf66ca715f70842b4a7ad4f2d8610b80e4b65e1fb02bada91b3f9e930"
      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOneWithTheWrench/go-fly/releases/download/v0.1.5/go-fly_linux_arm64.tar.gz"
      sha256 "3b8a1ccc5206f9d80fd0c9715f2b1e572143960bc79c9217165c51d6a8c8ecb8"
      define_method(:install) do
        bin.install "fly"
      end
    end
  end
end
