# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillSelector < Formula
  desc "Manage shared skills across supported coding agents"
  homepage "https://github.com/TheOneWithTheWrench/skill-selector"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheOneWithTheWrench/skill-selector/releases/download/v0.0.1/skill-selector_darwin_amd64.tar.gz"
      sha256 "af49904883f7d93bd27aba45b0ecd8b5ba8448ce3fdafc2b8e3e72d66c0c5bfd"

      define_method(:install) do
        bin.install "skill-selector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheOneWithTheWrench/skill-selector/releases/download/v0.0.1/skill-selector_darwin_arm64.tar.gz"
      sha256 "87bc59bed298eba18897061df5517cf632dedb5b2186c2e7c551485c5881c0e4"

      define_method(:install) do
        bin.install "skill-selector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOneWithTheWrench/skill-selector/releases/download/v0.0.1/skill-selector_linux_amd64.tar.gz"
      sha256 "2bfd2a5318cf0eb5e7b1c3a0a4dbec41693f25376ccf8bf6ae90c50fc9d3efcf"
      define_method(:install) do
        bin.install "skill-selector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheOneWithTheWrench/skill-selector/releases/download/v0.0.1/skill-selector_linux_arm64.tar.gz"
      sha256 "d4117019e479a1706d67715cb350ff4f37a4d10fd6eb03c9cc30563ab164ab8d"
      define_method(:install) do
        bin.install "skill-selector"
      end
    end
  end
end
